### ISSUE TITLE
Comparison with shinymanager

### ISSUE THREAD

**Issue by Robinlovelace** [bczernecki/shinylogin#1]
Just noticed this repo, I spent ages looking and finally found something that works: https://github.com/datastorm-open/shinymanager/

Flagging in case you've not seen this before, comparison could provide food for thought, good to see more in this area in any case.

**Comment by bczernecki** [comment]
Wow! That was quick. Yes, this is what I was looking for.
Thanks @Robinlovelace 👍 !

**Comment by Robinlovelace** [comment]
Glad it's of use : ) Communication, good.
